comments = [
    {
        "user_id": 2,
        "post_id": 1,
        "text": "These are so cool! I wish I had woodcarving as a skill, might need to pick it up",
        "url": None,
    },
    {
        "user_id": 3,
        "post_id": 1,
        "text": "You got a site? Wouldn't mind trying to pick me up one of these",
        "url": None,
    },
    {
        "user_id": 2,
        "post_id": 2,
        "text": "Yo is that dead rising? I played that game to death!",
        "url": None,
    },
    {
        "user_id": 3,
        "post_id": 2,
        "text": "Love me some zombies, man",
        "url": None,
    },
    {
        "user_id": 2,
        "post_id": 3,
        "text": "There is no way you did this in 152 hours...",
        "url": None,
    },
    {
        "user_id": 3,
        "post_id": 3,
        "text": "YOOOOOOOOOOOOO that looks crazy good!",
        "url": None,
    },
    {
        "user_id": 2,
        "post_id": 4,
        "text": "Wait a second...OHHHH I get it now",
        "url": None,
    },
    {
        "user_id": 3,
        "post_id": 4,
        "text": "What a classic",
        "url": None,
    },
    {
        "user_id": 1,
        "post_id": 5,
        "text": "Awwww, so cute",
        "url": None,
    },
    {
        "user_id": 3,
        "post_id": 5,
        "text": "Those are some fine lookin' dogs",
        "url": None,
    },
    {
        "user_id": 1,
        "post_id": 6,
        "text": "My cat is the same way",
        "url": None,
    },
    {
        "user_id": 3,
        "post_id": 6,
        "text": "This is why i'm a dog lover, haha",
        "url": None,
    },
    {
        "user_id": 1,
        "post_id": 7,
        "text": "Make sure you stay safe out there",
        "url": None,
    },
    {
        "user_id": 3,
        "post_id": 7,
        "text": "Been meaning to get me a bike like that",
        "url": None,
    },
    {
        "user_id": 1,
        "post_id": 8,
        "text": "I agree with ya man, it's crazy how nature can be",
        "url": None,
    },
    {
        "user_id": 3,
        "post_id": 8,
        "text": "I really hope that's not near me",
        "url": None,
    },
    {
        "user_id": 1,
        "post_id": 9,
        "text": "Wow...just, wow",
        "url": None,
    },
    {
        "user_id": 2,
        "post_id": 9,
        "text": "Crude, but still an oldie, I like it",
        "url": None,
    },
    {
        "user_id": 1,
        "post_id": 10,
        "text": "Good on you man",
        "url": None,
    },
    {
        "user_id": 2,
        "post_id": 10,
        "text": "Will definitely look out for that place",
        "url": None,
    },
    {
        "user_id": 1,
        "post_id": 11,
        "text": "Dude, that is amazing",
        "url": None,
    },
    {
        "user_id": 2,
        "post_id": 11,
        "text": "Huh, I didn't even know what an Osprey is. I'll need to be on the lookout next time I go traveling",
        "url": None,
    },
    {
        "user_id": 1,
        "post_id": 12,
        "text": "Stealing this for my dnd sessions",
        "url": None,
    },
    {
        "user_id": 2,
        "post_id": 12,
        "text": "What I wouldn't give for a nice brew out on the seas",
        "url": None,
    },
]
